Server:
  Port: 3000
  Mode: debug
  Domain: localhost:3000
  WebDomain: localhost:5173

Postgres:
  Host: localhost
  Username: username
  Password: password
  DBName: database
  Port: 5432
  SSLMode: disable
  TimeZone: Asia/Shanghai

Zap:
  Level: debug
  Prefix: "[jianji-server] "
  Directory: "log"
  Format: "console"
  ShowLine: true
  LogInConsole: true

Email:
  SMTPServer: smtp.xxx.com
  SMTPPort: 465
  From: xxx@xxx.com
  Password: AAAAAABBBBBBBB
  DefaultSubject: 简记

Redis:
  Network: tcp
  Addr: localhost:6379
  Password: ""
  DB: 1

MaxMind:
  LicenseKey: ""
